# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "ehci_pci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/af985ceb-f172-43d0-864f-7c8f4fc8ec88";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:3" "noatime" "autodefrag" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/af985ceb-f172-43d0-864f-7c8f4fc8ec88";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:3" "noatime" "autodefrag" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/af985ceb-f172-43d0-864f-7c8f4fc8ec88";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:3" "noatime" "autodefrag" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2C59-433B";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
